### ISSUE TITLE
Unwanted <br> in <span>

### ISSUE THREAD

**Issue by ShahriarKh** [dvtng/react-loading-skeleton#144]
I don't know why I get a `<br>` inside my skeleton, which is making an unwanted margin below it.

### Output
![image](https://user-images.githubusercontent.com/31452340/184669737-8eee644b-5ba5-467b-a7f7-a8fb766d4c05.png)
```html
<span aria-live="polite" aria-busy="true">
    <span class="react-loading-skeleton image" style="--animation-direction:reverse;height:120px;--base-color:#d4d4d8;--highlight-color:#e4e4e7">‌
    </span>
    <br>
</span>
```
### Code
```jsx
<Skeleton className={css["image"]} />
```
```scss
.image {
    border-radius: $round * 2 $round * 2 0 0;
    display: block;
    padding-top: 90%;
    width: 100%;
}
```

I'm not sure why it's being added.

**Versions**
-   react-loading-skeleton version: 3.1.0
-   Browser version: Firefox Developer Edition 104, Chrome 104
