### ISSUE TITLE
Height is incorrect

### ISSUE THREAD

**Issue by jaripekkala** [dvtng/react-loading-skeleton#23]
https://codesandbox.io/embed/v888k169wl

The skeleton ends up being 1 pixel taller than given in props. A simple workaround is to override the skeleton element's line-height

```css
span {
    line-height: normal !important;
}
```
